### ISSUE TITLE
Impossible to revert a click on a checkbox/switch

### ISSUE THREAD

**Issue by zedrdave** [buefy/buefy#2899] opened 2020-09-18 09:19 UTC
### Overview of the problem

When cancelling a value update on a switch/checkbox, the element goes out of sync.

**Buefy** version: 2.6.11
**Vuejs** version: 0.8.20

### Steps to reproduce

- Create a `b-checkbox` connected to an external state through its `:value` property

- Assign an action through the checkbox' `@input` event.

- If ticking the checkbox needs to be validated in the `@input` function (eg  pop a confirmation dialog that lets user cancel), there is no way to do that. Updating the state in the event function is not effective, and the checkbox goes out of sync.

I'm using `:value` (rather than `v-model`) synced to a Vuex state, updated through a Vuex action+ajax, triggered by `@input` (not directly relevant to the problem, but explains why I need `:value/@input`, rather than `v-model`):

Wouldn't an elegant solution be to look for an optional return value from @input and cancel input update accordingly? (basically similar to how native.input works)

**Comment by jtommy** [comment] 2020-09-19 16:55
Can you reproduce it on codepen or similar?

**Comment by zedrdave** [comment] 2020-09-21 08:24
I don't think I'll have the time this week, but maybe @lutzklai?

**Comment by lutzklai** [comment] 2020-09-22 02:34
Sure thing, here is a [stackblitz](https://stackblitz.com/edit/buefy-issue-1999?file=app.js) I made. I went ahead and added the b-switch because it has the same behavior and that is the component I am having issues with.

So if you click on the checkbox then click cancel on the prompt you'll see the checkbox state is still true however the checkbox UI has updated to look like its false.

My app's case is pretty similar to @zedrdave. The user has an "availability" switch that they can click to become available or unavailable. The switche's state comes from vuex and when the user clicks the switch the app dispatches an api to update the user's status in the DB. If for some reason this api request fails, I do not want to update the UI of the switch

**Comment by jciechowski** [comment] 2020-10-27 12:06
Run into same issue today with b-switch. Maybe someone figured out some workaround?

**Comment by lutzklai** [comment] 2020-10-28 16:11
@jciechowski Thinking about this a bit more. I was able to get this to work by using the `prevent` modifier.

```html
<b-checkbox
    :value="checkboxValue"
    @click.native.prevent="toggleCheckbox"
>
```

See this [stackblitz](https://stackblitz.com/edit/buefy-issue-1999-workaround?file=app.js)

**Comment by zedrdave** [comment] 2020-10-28 16:27
@lutzklai Awesome workaround (could swear I tried something similar back then without getting it to work)… Thanks!

**Comment by jtommy** [comment] 2020-10-28 17:32
@lutzklai cool! I don't know what I can do natively on Buefy to be honest..

**Comment by wesdevpro** [comment] 2024-01-20 03:04
> @jciechowski Thinking about this a bit more. I was able to get this to work by using the `prevent` modifier.
> 
> ```
> <b-checkbox
>     :value="checkboxValue"
>     @click.native.prevent="toggleCheckbox"
> >
> ```
> 
> See this [stackblitz](https://stackblitz.com/edit/buefy-issue-1999-workaround?file=app.js)

Closing because a workaround was found!

**Closed by wesdevpro** 2024-01-20 03:04 UTC
Labels: workaround
