### ISSUE TITLE
IE-11 modal and Dialog body overflow scroll not visible 

### ISSUE THREAD

**Issue by KishorNamdeo** [buefy/buefy#734] opened 2018-03-29 07:13 UTC
when modal or dialog open in IE then the body section scroll not visible and footer section hide
![image](https://user-images.githubusercontent.com/30079342/38075070-adc55756-334e-11e8-81c7-0b788aaeddc4.png)

**Comment by adrlen** [comment] 2018-03-29 07:56
Duplicate of #519

**Closed** 2018-03-29 11:50 UTC
