### ISSUE TITLE
b-table: selected prop should be reset if item was removed from data array

### ISSUE THREAD

**Issue by s-nesbigall** [buefy/buefy#1882] opened 2019-10-17 08:33 UTC
### Overview of the problem

If the _selected_ prop is filled with the selected data item in a b-table and this item gets removed from the _data_ array, (In my opinion) the _selected_ should be null/reset and the _select_ event should be triggered. 

**Buefy** version: [0.8.5]
**Vuejs** version: [2.6.10]
**OS/Browser**:

### Description

Changing the _data_ array should always update dependant properties.

### Steps to reproduce

From the # Selection example of the documentation:
- Add a second button to remove the first item in the array:

`<button 
    class="button field is-danger" 
    @click="remove"
    :disabled="data.length === 0">
    <b-icon icon="close"></b-icon>
    <span>Remove first</span>
</button>`

and a method remove:
`methods: {
    remove: function(){
      this.data.shift();
    }
  }`

### Expected behavior

In the example the second item is selected, so I expect after two clicks on the remove button the selected item is removed AND the _selected_ is null.

### Actual behavior

After two clicks the item is removed, but the _selected_ property still hold the removed item.

**Comment by service-paradis** [comment] 2019-10-17 12:08
Is this a duplicate of https://github.com/buefy/buefy/issues/1826?

**Closed** 2019-10-17 12:14 UTC

**Comment by s-nesbigall** [comment] 2019-10-17 12:18
Hi,
I think it is the same problem:
If the data changes other b-table props are not (re)set correctly.
#1826 mentiones the checkable feature and the checked-rows prop, I stumbled over this using the selected prop.

Sorry for the duplicate, prior I searched for b-table issues and the component is not mentioned in #1826.
