### ISSUE TITLE
Adding ConfigProgrammatic reverses bundle size gains

### ISSUE THREAD

**Issue by bhaeussermann** [buefy/buefy#3124] opened 2021-01-04 08:40 UTC
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11

### Description

Changing my project to include individual components instead of the full bundle leads to the vendors-js bundle size being reduced from 463.9 KiB down to 258.8 KiB. 

But this is without registering the font-awesome icon pack. It appears that using individual components, I must use `ConfigProgrammatic` to do that (see [Constructor options](https://buefy.org/documentation/constructor-options)). The problem is that when I set options using `ConfigProgrammatic` it seems to undo the bundle size gains even when specifying an empty options object:

```
ConfigProgrammatic.setOptions({ });
Vue.use(Table);
Vue.use(Input);
```

It brings the vendors-js bundle size back up to 467.1 KiB, which is actually a bit worse than including the full bundle!

### Steps to reproduce

1. Create a new Vue 2 app using Vue CLI.
1. Import the buefy package: `npm install buefy --save`
1. Import individual components as on the ["Getting Started" page](https://buefy.org/documentation/start). My main.ts looks as follows:
```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import { Table, Input } from "buefy";
import "buefy/dist/buefy.css";

Vue.config.productionTip = false;

Vue.use(Table);
Vue.use(Input);

new Vue({
  router,
  render: h => h(App)
}).$mount("#app");
```
1. Run a build: `npm run build`
1. The reported vendors-js bundle size is relatively small
1. Add `ConfigProgrammatic.setOptions({ });` before the `Vue.use()` statements.
1. Run a build: `npm run build`

### Expected behavior

The vendors-js bundle size must not increase significantly after adding `ConfigProgrammatic`

### Actual behavior

The vendors-js bundle size explodes after adding `ConfigProgrammatic`

**Comment by jtommy** [comment] 2021-01-05 13:19
It has been fixed in other version but probably no

**Comment by bhaeussermann** [comment] 2021-01-05 18:02
@jtommy Thanks! Which version has it been fixed in and what is "no"?

**Comment by jtommy** [comment] 2021-01-09 10:46
I thought it but probably isn't working well right now

**Comment by riker09** [comment] 2021-01-18 07:01
I'm facing the same issue. We're developing a web app that will be running on slow and unreliable network connections frequently where every KB download size matters. Our vendor bundle is currently ~130 KB.

We decided to drop support for FontAwesome and use SVG Icons instead. We don't need to include several hundred icons in a font file when we're only using ~10 of them. This is our `main.ts` application entrypoint:

```typescript
import 'reflect-metadata';
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import './assets/scss/bulma.scss';
import BuefyIconRenderer from '@/components/buefy-icon-renderer.vue';

import { ConfigProgrammatic } from 'buefy';


class AppBootstrap {
  constructor () {
    this.loadVueApp();
  }

  private loadVueApp () {
    Vue.component('buefy-icon-renderer', BuefyIconRenderer);

    ConfigProgrammatic.setOptions({
      defaultIconComponent: 'buefy-icon-renderer'
    });

    Vue.config.productionTip = false

    new Vue({
      router,
      render: h => h(App)
    }).$mount('#app')
  }
}

new AppBootstrap();

```

Buefy components are included inside our components like this:

```vue
<template>
  <div id="app">
    <div id="nav">
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link>
    </div>
    <router-view/>
    <div id="myModel">
      Tagged:
      <BTag>foo</BTag><BTag class="is-primary">bar</BTag>
    </div>
  </div>
</template>

<script lang="ts">
import Component from 'vue-class-component';
import Vue from 'vue';
import { BTag } from 'buefy/dist/esm/tag';

@Component({
  name: 'App',
  components: {
    BTag,
  }
})
export default class App extends Vue {
}
</script>
```

However, the webpack-bundle-analyzer reports, that all of Buefy's components have been loaded and the vendor chunk is around 114 KB. When I remove the `BuefyIconRenderer` component from the `main.ts` the bundle size drops down to 51 KB.

What needs to be done to tackle this issue? How can I help?

**Comment by jtommy** [comment] 2021-01-18 07:08
There is an issue with config but are you importing b-tag in this way ?

**Comment by riker09** [comment] 2021-01-18 07:37
Is this not "de way"? Sorry, I've read so many different posts on this topic and I must have copied it from somewhere. It does work, however. 😄

**Comment by jtommy** [comment] 2021-01-19 20:32
Yes it works but you can use import each component plugins

**Comment by riker09** [comment] 2021-01-20 05:57
Can you please give an example of your preferred solution?

**Comment by jtommy** [comment] 2021-01-20 07:15
```
import { Input } from 'buefy'

Vue.use(Input)
```

**Comment by TheStopsign** [comment] 2021-01-31 23:05
![image](https://user-images.githubusercontent.com/45616121/106400726-43746580-63ee-11eb-86ef-9dbf636479cd.png)

[Bundlephobia](https://bundlephobia.com/result?p=buefy@0.9.4) confirming that ConfigProgrammatic has higher gzip size. Is there an alternate way without ConfigProgrammatic to modify [constructor options](https://buefy.org/documentation/constructor-options)?

**Comment by MartinodF** [comment] 2021-02-02 18:14
I just hit the same issue while trying to reduce the bundle size by using svg icons.

I can confirm that importing the entire configuration object directly from dist and editing it directly doesn't cause the same issue. Too bad it's not really a viable workaround!

```js
import { c } from 'buefy/dist/esm/chunk-ce068f0a';
c.defaultIconComponent = 'Icon';
```

**Comment by jtommy** [comment] 2021-02-02 19:28
Yes I know, I should investigate about it

**Comment by MartinodF** [comment] 2021-02-04 17:09
Ok, I'm totally not sure about any of the following, but here it goes...

I believe the issue is due to the fact that `dist/esm/index.js` contains ConfigComponent as inlined code:
```js
// lines 156-163
var ConfigComponent = {
  getOptions: function getOptions() {
    return config;
  },
  setOptions: function setOptions$1(options) {
    setOptions(merge(config, options, true));
  }
};
```

This means that both getOptions and setOptions are closures with, potentially, access to any variable declared above (which includes every component) and so defeat any possibility of tree shaking the library when imported.

Having never used Rollup, my first approach has been adding a new entry to rollup.config.js:
```patch
diff --git a/rollup.config.js b/rollup.config.js
index 5da0fb1d..9baf9bc0 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -30,6 +30,7 @@ const components = fs
 const entries = {
     'index': './src/index.js',
     'helpers': './src/utils/helpers.js',
+    'config': './src/utils/ConfigComponent.js',
     ...components.reduce((obj, name) => {
         obj[name] = (baseFolder + componentsFolder + name)
         return obj
```

This does produce a separate file, removes the inlined ConfigComponent from index.js and solves the tree shaking issue.

Would you consider this an acceptable fix? Do you want me to create a PR?

Thank you for your time!

**Comment by jtommy** [comment] 2021-02-04 17:25
Oh yes, you are right. Of course a PR!! @MartinodF

**Closed** 2021-02-04 18:41 UTC
Labels: bug
