### ISSUE TITLE
Table headers disappear during backend-pagination when the items in the page are less than the previous

### ISSUE THREAD

**Issue by EricRabil** [buefy/buefy#2660] opened 2020-07-09 16:47 UTC
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.11
**OS/Browser**: macOS Catalina 10.15.5 / Chrome 83.0.4103.116

### Description

I believe there's been a regression since #1049 involving defining columns through `<b-table-column label="Label">`, and the afflicted logic is here: https://github.com/buefy/buefy/blob/1f4730fde6b2f351afacb15c0e6fc316116c2439/src/components/table/TableColumn.vue#L53-L66

This hook is being called before the previous columns have been removed from `newColumns`, and as a result, the columns are no longer present when the new number of items are rendered.

### Steps to reproduce

1. Use `backend-enabled` pagination features
2. Use computed columns through the `label` attribute on `b-table-column`
3. Navigate to the last page of the data, and ensure the number of items is less than the number in a full page.

### Expected behavior

The columns do not disappear

### Actual behavior

The columns do disappear.

The problem does not occur when columns are rendered in mobile mode. Make sure to view the codesandbox at a desktop viewport width.

https://codesandbox.io/s/buefy-template-3zlk3?file=/src/App.vue

I'm unsure how this fixes it, and it is not a proper solution, however clearing all data and waiting for the next Vue tick before assigning the next page of data does fix the problem. This is included in the codesandbox.

With asynchronously loaded data, this is my temporary solution:
```ts
public async loadAsyncData() {
    const newResults = await AdminUserSDK.searchUsers({ query: this.query, page: this.page, sort: this.sortOption });
        
    this.result = { total: 0, results: [] };
    await this.$nextTick();
    this.result = newResults;
}
```

**Comment by jtommy** [comment] 2020-07-09 18:43
It should be fixed in the next version

**Closed by jtommy** 2020-07-09 18:43 UTC

**Comment by terenceng2010** [comment] 2020-08-14 08:06
The issue is not only related to async, I also can reproduce the issue when the table list is changing from, let's say 3 items to 2 items, and my workaround is also using nextTick.

https://codesandbox.io/s/compassionate-bell-5lu7e?file=/index.html
