### ISSUE TITLE
Form Elements in Carousel does not work

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#2339] opened 2020-03-23 19:26 UTC
### Overview of the problem

**Buefy** version: 0.8.13
**Vuejs** version: 2.6.11
**OS/Browser**: Any

### Description

I'm using the carousel element for different purposes (not only for images). I have one carousel where I give the possibility to edit some text using a textarea. Right now, clicking the textarea input does not give the focus to the element. Therefore, we cannot write in it.

### Steps to reproduce

1. Add a carousel element to a page
2. Add a `b-input` of type `textarea` in a slide
3. Click on the textarea to add some text

### Expected behavior

It would be really cool if we could use the carousel for more than just images as expected by looking at the documentation. So I expected the form elements (like a textarea) to be working.

### Actual behavior

As you can see in the following link, it does not work:
https://codepen.io/service-paradis/pen/BaNqBWm?editable=true&editors=101

**Comment by apolokaklab** [comment] 2020-03-25 23:03
@service-paradis me need investigation.
I see this related of drag event, so for now you can added `:has-drag="false"` to do that :wink:

**Comment by service-paradis** [comment] 2020-03-26 13:15
Thanks for your answer @apolokaklab :)
I'm using the `:has-drag="false"` as a workaround right now.

It looks like this is causing the issue:
https://github.com/buefy/buefy/blob/dev/src/components/carousel/Carousel.vue#L313

**Comment by apolokaklab** [comment] 2020-04-19 10:28
@jtommy i will to refactor but i need news break changes.
@service-paradis i think can replace with `event.target.tagName === 'IMG' && event.preventDefault()`

**Comment by jtommy** [comment] 2020-04-19 10:29
Ok no problem, make a breaking PR

**Comment by belvederef** [comment] 2020-05-04 19:50
Any update on this guys? I am experiencing this issue on a `<select>` input inside the carousel component. It is indeed caused by `event.preventDefault()`, called on `mousedown`.

**Comment by Tofandel** [comment] 2020-06-25 15:25
Current workaround is to add `@mousedown.native.stop` to your input

**Comment by Tofandel** [comment] 2020-06-25 15:27
Why do we preventDefault on the mousedown event anyways? It's not like it's got any side effects

**Comment by belvederef** [comment] 2020-06-25 15:34
> Current workaround is to add `@mousedown.native.stop` to your input
> https://codepen.io/Tofandel/pen/KKVqxMz?editable=true&editors=101

I tried your codepen but I do not see any difference with the current state of things. When I click in the input the slide changes automatically.

**Comment by Tofandel** [comment] 2020-06-25 15:43
What browser are you using, it works for me

**Comment by belvederef** [comment] 2020-06-25 15:51
Chromium Version 83.0.4103.61 (Official Build) Arch Linux (64-bit). Try clicking on one of the arrows and then clicking in the input area again. Once you change a slide, every click in the input area triggers changes the current slide.

**Comment by Tofandel** [comment] 2020-06-25 15:53
That's interesting, the dragX is not reset.. So I guess you also need to add `@mouseup.native.stop`
Will be fixed in #2619

**Comment by Tofandel** [comment] 2020-06-25 16:01
Since there might potentially be other tags than image, how about we prevent the drag from elements that have the class 'no-drag'?

**Comment by service-paradis** [comment] 2020-06-25 16:50
Or the opposite, drag only element having the draggable attributes (https://www.w3schools.com/tags/att_global_draggable.asp#:~:text=HTML%20draggable%20Attribute&text=The%20draggable%20attribute%20specifies%20whether,Drop%20tutorial%20to%20learn%20more.)

**Comment by Tofandel** [comment] 2020-06-25 17:18
Yeah I just tried, it works well without breaking existing code because images are draggable by default

**Comment by jtommy** [comment] 2020-06-26 11:38
Close https://github.com/buefy/buefy/pull/2619

**Closed by jtommy** 2020-06-26 11:38 UTC
Labels: workaround
