### ISSUE TITLE
Select not updating when table data is changed.

### ISSUE THREAD

**Issue by gazzer82** [buefy/buefy#152] opened 2017-07-03 21:27 UTC
### Overview of the problem

**Buefy** version: [0.4.4]
**Vuejs** version: [2.3.3]
**OS/Browser**: OSX, Chrome/Safari/Firefox

### Description

I have a filtered dataset for my table, and a select that updates the values of data for it's row when selected, causing that row to disappear from the table as it no longer meets the filter criteria.

### Problem 

By default the select has no value defined, just showing the default "Select One" that i have defined for an empty selection. However if the row that is updated is at the top of the table, when the row that was in 2nd place becomes the top row, it's select inherits the value of the previous row, rather than staying as "Select One", despite the underlying data still being correct.

The other data in the row does render correctly, it's just the select that doesn't.

The issue doesn't seem to reproduce itself with other rows.

Flipping to a different filter option, so changing the underlying data, and then flipping back fixed the issue.

### Steps to reproduce

Setup a table with a computed data source, that itself comes from a getter on a Vuex store.

In the row template, create a column that contains a select box that in in a separate sub-component, this also has a computed data source, that itself comes from a getter on a Vuex store providing the values for the dropdown. Set the default (no value) setting for the select to ""Select One"

<img width="1302" alt="screen shot 2017-07-03 at 22 12 09" src="https://user-images.githubusercontent.com/1923535/27808255-82d68bb6-603e-11e7-9d59-6f8068abfa8b.png">

Set the selected option for the dropdown to come from a computer value, that comes from matching a value in the dropdown datasource with an ID passed through as a prop from the row containing it (props.row.something)

Change the value of the select box in the first row to update something on the row, causing it to no longer be in the values returned by the getter datasource for the table.

<img width="1299" alt="screen shot 2017-07-03 at 22 12 16" src="https://user-images.githubusercontent.com/1923535/27808258-886f1606-603e-11e7-8fd5-061366bb22b4.png">

### Expected behavior

Row should disappear, and the row below it should move to the top of the table with it's select still set to "Select One"

### Actual behavior

The select inherits the previously selected value from the row that has disappeared.

<img width="1300" alt="screen shot 2017-07-03 at 22 12 25" src="https://user-images.githubusercontent.com/1923535/27808262-8b0b6766-603e-11e7-9789-f9c6cdf88427.png">

Images attached to describe the issue better than my rambling.

Thanks

Gareth

**Comment by rafaelpimpa** [comment] 2017-07-04 11:21
Well, I have no idea on how to fix that TBH, do you? Maybe if you have a more simple way to reproduce would be easier.

**Comment by gazzer82** [comment] 2017-07-05 05:41
Hi @rafaelpimpa in all honesty no, I've only just started out with Vue/Vuex so the component lifecycle is still a bit of a mystery to me. I come from React/Redux where things where a little more explicit/overridable, but that doesn't seem to be the case in Vue.

I can setup a sandbox version of the app I'm working on and give you access to it if you like, so you can see what I'm talking about, can also add you to the git repo if that helps?

I've decided to work on the rest of the app whilst my brain is pondering the problem and I'm going to circle back to it once I've got the rest of the app in a better state. But it doesn't seem to come down to the dropdown essentially not re-rendering itself, so somehow not getting told that it's data source has changed.

If you had any suggestions for way for me to test that theory I am more than willing to take a deep dive into it, my troubleshooting skills in Vue are not that strong, yet!

Thanks

Gareth

**Comment by rafaelpimpa** [comment] 2017-07-05 11:17
``I can setup a sandbox version of the app I'm working on and give you access to it if you like, so you can see what I'm talking about, can also add you to the git repo if that helps?``

Sure, would help a lot.

**Comment by jaybeecave** [comment] 2017-07-10 01:16
Are you using an integer as the value.. Seems there is a bug that if you use an int as an option value and also the b-select binding value then things don't update as expected.

Try something like this to see if it fixes and let me know if it does.

```
          <b-select :value="(job.HistoricStatus+'')">
            <option value="0">Quoting</option>
            <option value="1">Part Payment 1</option>
            <option value="2">Part Payment 2</option>
            <option value="3">Part Payment 3</option>
            <option value="4">Part Payment 4</option>
          </b-select>
```

Originally I wrote this code as (if my description didn't quite make sense)
```
          <b-select :value="job.HistoricStatus"> <!-- this is an integer -->
            <!-- bind the values to a number with : rather than passing a string -->
            <option :value="0">Quoting</option>
            <option :value="1">Part Payment 1</option>
            <option :value="2">Part Payment 2</option>
            <option :value="3">Part Payment 3</option>
            <option :value="4">Part Payment 4</option>
          </b-select>
```

**Comment by rafaelpimpa** [comment] 2017-07-10 13:38
Humm... both examples works OK running individually, are you saying the behavior is differnet when within a table? Can you give me a full example?

**Comment by Tirke** [comment] 2017-08-04 11:30
@rafaelpimpa I think you should close this issue, because looking at the screenshots provided, he is using [another package to handle his select](https://github.com/monterail/vue-multiselect).
This package does have some flaws and issue related to value changing and the issue is surely coming from this rather than from buefy ....

**Comment by gazzer82** [comment] 2017-08-04 11:32
@Tirke I am currently as I wanted some auto-search functionality, but I had exactly the same issue with the Buify select.

In fact, I initially tried the alternative package to see if it would resolve the issue, which it didn't.

**Comment by Tirke** [comment] 2017-08-04 11:38
@gazzer82 Ok, so it's quite embarrassing 😞 ... If you still need some help on this issue I have some experience with this kind of issues but you may have find a workaround since this issue is nearly a month old.

**Comment by rafaelpimpa** [comment] 2017-08-07 12:36
@gazzer82 did you find a workaround?

**Comment by gazzer82** [comment] 2017-08-07 12:54
The only way I could find around it was to very quickly swap the whole underlying dataset to a dummy empty set and back again, not really ideal but it works.

On 7 Aug 2017, 13:36 +0100, Rafael Beraldo <notifications@github.com>, wrote:

@gazzer82<https://github.com/gazzer82> did you find a workaround?

**Comment by Tirke** [comment] 2017-08-07 13:16
Tbh it's currently quite hard to provide help because we do not have any code examples and I'm not really sure I fully understand your current situation.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-24 17:32
@jtommy should we close it?

**Closed** 2019-07-24 18:55 UTC
Labels: contribution welcome, need more info
