### ISSUE TITLE
checkHtml5Validity not called on input when value changed: error stays in the UI despite value present

### ISSUE THREAD

**Issue by darkylmnx** [buefy/buefy#3752] opened 2022-06-20 01:56 UTC
### Overview of the problem

**Buefy** version: [0.9.19]
**Vuejs** version: [2.6.14]
**OS/Browser**:

### Description

When a field with required attribute is emptied after it has been filled, there's an error which is normal.
When you fill in the field via the value attribute or v-model (without user interacting), the error stays.

It's because the validity check is only done if the valud changed through the input event,
it doesn't check the validity if the value changed.

https://github.com/buefy/buefy/blob/dev/src/components/input/Input.vue#L265

As seen here, `updateValue` which does the validity check is only called in `onInput` or `onChange` methods,
it's not called in the watch or in the value setter.

Not called here.
https://github.com/buefy/buefy/blob/dev/src/components/input/Input.vue#L213
Not called here either
https://github.com/buefy/buefy/blob/dev/src/components/input/Input.vue#L115

### Steps to reproduce

Here's a jsfiddle : https://jsfiddle.net/hs9xtzny/

1. click / focus in the input then go out without entering anything, you should see an error (that's normal)
2. click on the "generate" button
3. your should see the input filled but the error stays

### Expected behavior

I expect to not see any error if my value is correct, wether the user set it or the code set it.

### Actual behavior

See above and here : https://jsfiddle.net/hs9xtzny/

**Comment by friedow** [comment] 2022-06-22 10:08
This is caused by the PR https://github.com/buefy/buefy/pull/3712 which was merged in 0.9.20. Until this is fixed you can solve your problem by downgrading to v0.9.19.

### Cause Description
https://github.com/buefy/buefy/pull/3712 causes an error in the validation which was originally fixed with https://github.com/buefy/buefy/pull/3430. Since https://github.com/buefy/buefy/pull/3712 reverts a part of https://github.com/buefy/buefy/pull/3430, the error reappears.

**Comment by jtommy** [comment] 2022-06-22 17:18
@friedow would you like to make a PR?

**Comment by friedow** [comment] 2022-06-23 06:03
Sure I can look into it :). This will probably take a few minutes to figure out how to preserve both functionalities (https://github.com/buefy/buefy/pull/3430 & https://github.com/buefy/buefy/pull/3712).

**Comment by neonanal** [comment] 2022-10-17 06:11
Hello,
I'm trying to call  `this.$refs.input.checkHtml5Validity()` to  validate text input that has value set programmatically (i.e. w/o user input), but cannot trigger `valid=false` state unless I modify input value from keyboard, i.e. add or delete symbol. Neither focus nor blur nor calling `this.$refs.input.checkHtml5Validity()` trigger validationc check. Is it a feature or I'm doing something wrong? 

Using latest 0.9.22, tried 0.9.19 -- same behaviour.

**Comment by neonanal** [comment] 2022-10-17 07:08
Actually, disregard my message, seems like some quirk of html5 `checkValidity()` fn, as I cannot get false from it even with bare `<input>` tag unless I interact with it. Will look deeper and post back.

**Closed** 2023-06-10 05:37 UTC

**Comment by glumb** [comment] 2023-09-08 12:12
I'm still experiencing the same behaviour with 'min' and 'max' limitations:

If a value is entered once that is outside the range, the notification does not go away even if numbers are input in the valid range.

![image](https://github.com/buefy/buefy/assets/3062564/c95243e2-9969-4db2-96e5-759cab549e24)


```js
 <b-field>
    <b-input
      v-model.number="enteredValue"
      type="number"
      :min="100"
      :step="100"
      :max="900" />
    <p class="control">
      <span class="button is-static">{{ name }}</span>
    </p>
    <p  class="control">
      <b-button title="reset value" icon-left="undo" @click="onClickReset" />
    </p>
  </b-field>
```

**Comment by wesdevpro** [comment] 2023-09-08 21:37
> ### Overview of the problem
> **Buefy** version: [0.9.19] **Vuejs** version: [2.6.14] **OS/Browser**:

@glumb  What version are you using? And what browser?

**Comment by glumb** [comment] 2023-09-09 06:55
@wesdevpro I'm using `version": "0.9.23"` and I tested on Chrome and Safari, which both show this behaviour.

**Comment by wesdevpro** [comment] 2023-09-11 21:34
> @wesdevpro I'm using `version": "0.9.23"` and I tested on Chrome and Safari, which both show this behavior.

Thank you! Can you open up a new Issue pertaining to this issue?

**Comment by kikuomax** [comment] 2023-09-12 02:58
@wesdevpro I found there are two separate problems:
1. `Field` containing multiple child components (addons) never resets its validation status (`newType`) once it is set. @glumb this is what happens if you enter a wrong value in the field in your example
2. `Input` does not check validity if the value is changed without user interaction. @glumb this is what happens if you press "reset value" button in your example

Both are seemingly easy fixes, though, the second behavior looks intentional to address this very old issue #1221.

**Comment by kikuomax** [comment] 2023-09-13 01:23
@wesdevpro @glumb I have opened two issues:
1. #3883
2. #3884

@glumb I have borrowed your example as it is simple and relevant for both of the cases.
