### ISSUE TITLE
Gap between Upload and Filename in Field with horizontal layout

### ISSUE THREAD

**Issue by poulinjulien** [buefy/buefy#2382] opened 2020-04-06 22:31 UTC
### Overview of the problem

**Buefy** version: 0.8.15
**Vuejs** version: 0.7.5
**OS/Browser**: Windows 10 - Edge, Firefox

### Description

When used in an horizontal field, there is a gap between the Upload button and the Filename span.

### Steps to reproduce

https://codepen.io/poulinjulien/pen/ExjqXeb

### Expected behavior

The Filename span should be right next to the Upload button.
![image](https://user-images.githubusercontent.com/1919739/78611292-e90a8700-7866-11ea-986f-2e86c55012c3.png)

### Actual behavior

There is a gap between the Upload button and the Filename span.
![image](https://user-images.githubusercontent.com/1919739/78611348-07708280-7867-11ea-841e-62fe75ee0bbc.png)

**Comment by jtommy** [comment] 2020-04-13 21:48
It was only an example and the issue is relative to bulma

**Comment by wesdevpro** [comment] 2024-01-20 02:54
Closing because we cannot reproduce this issue even with the provided codepen. If you have any further information on how to reproduce this issue please reopen this issue. Thank You!

**Closed by wesdevpro** 2024-01-20 02:54 UTC
Labels: bulma
