### ISSUE TITLE
Buefy package error in Nuxt Js?

### ISSUE THREAD

**Issue by umarfarook882** [buefy/buefy#722] opened 2018-03-24 17:15 UTC
Hi Team,
   I am using  ``"nuxt-buefy": "0.0.4",`` I have installed and configured as per the doc in [Beufy](https://buefy.github.io). When i am run ``npm in dev mode``. I getting this error **HTMLElement is not defined**. Could anyone let me know what am i missing in installation?

```{ ReferenceError: HTMLElement is not defined
    at Object.defineProperty.value (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:103177)
    at t (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:377)
    at Object.<anonymous> (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:150180)
    at t (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:377)
    at Object.<anonymous> (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:132652)
    at t (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:377)
    at Object.defineProperty.value (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:78957)
    at t (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:377)
    at Object.<anonymous> (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:190387)
    at t (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:377)
    at e.exports.e (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:761)
    at /home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:772
    at n (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:143)
    at Object.<anonymous> (/home/demo/Downloads/Project/demo-website/node_modules/buefy/lib/index.js:1:254)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at r (/home/demo/Downloads/Project/demo-website/node_modules/vue-server-renderer/build.js:8330:16) statusCode: 500, name: 'ReferenceError' }
```

**Comment by wopian** [comment] 2018-03-24 17:20
Duplicate of #712 - has been fixed but not released yet

**Comment by umarfarook882** [comment] 2018-03-24 17:34
Thanks :) for the fast response. I hope next version will be releasing soon. Right now i fixed it temporary from the solution gave in the #712 .

**Comment by jtommy** [comment] 2018-03-24 17:53
Sorry guys. We'll release it as soon as possible

**Closed by jtommy** 2018-03-24 17:53 UTC
