### ISSUE TITLE
Dropdown Position Issue in Autocomplete Component

### ISSUE THREAD

**Issue by ivan006** [buefy/buefy#3871] opened 2023-08-03 16:21 UTC
### Overview of the problem

**Buefy** version:  "buefy": "^0.9.19",
**Vuejs** version:  "vue": "^2.6.11",
**OS/Browser**: [win10/crhome]

  
windows 10
### Description

I've encountered an issue with the positioning of the dropdown in the autocomplete component. Specifically, the dropdown has unexpected values for its CSS properties such as `position`, `top`, `left`, and `width`, leading to a misalignment in certain situations.

### Steps to reproduce

1. Create an autocomplete component 
2. Open the dropdown.
3. Observe the incorrect positioning.

Sorry to b so vauge perhaps I should try isolate the code so i can describe better how to reproduce it.
In the mean time this fact might help
- the autocomplete is in a modal

### Expected behavior

The dropdown should be properly aligned with the input field, following the provided `dropdownDirection` property.

### Actual behavior

The dropdown appears with the following incorrect CSS position values:
```css
position: absolute;
top: 960.075px;
left: 443.4px;
width: 884px;
max-width: 884px;
z-index: 99;
```
These values lead to a misalignment of the dropdown relative to the input field.

**Comment by ivan006** [comment] 2023-08-04 09:17
Somehow it had to do with that i set this prop 
      dropdown-position="bottom"

**Comment by kikuomax** [comment] 2023-12-05 02:21
@ivan006 If this is related to the following issue (PR), it will be fixed in the next release:
- #3865

**Comment by wesdevpro** [comment] 2024-01-20 02:26
> [@ivan006](https://github.com/ivan006) If this is related to the following issue (PR), it will be fixed in the next release:
> 
> * [fix(taginput): fix dropdown position when autocompleted and appended … #3865](https://github.com/buefy/buefy/pull/3865)

Closing because this issue should have been fixed. @ivan006 If you can reproduce this issue with the latest version of Buefy (Vue2) please reopen this issue with the steps to reproduce this problem. Thank You!

**Closed by wesdevpro** 2024-01-20 02:27 UTC
Labels: bug
