### ISSUE TITLE
Pagination styling broken on iOS Firefox/Safari/Chrome

### ISSUE THREAD

**Issue by nakedgun** [buefy/buefy#3405] opened 2021-07-04 18:07 UTC
### Overview of the problem

**Buefy** version: 0.9.8
**Vuejs** version: 2.6.11
**OS/Browser**: iOS 14.6 (tested on iPhone 11 Pro Max | iPhone SE) | Safari/Firefox/Chrome - latest versions

### Description

When paginating forward/backwards, the styling of the pagination UI breaks - numbers are invisible, text color of the current step is wrong:

![IMG_0675 2](https://user-images.githubusercontent.com/5262234/124394054-7038eb80-dcb2-11eb-9516-7af7774cc470.PNG)

### Steps to reproduce

1. On iOS firefox/chrome or safari, visit: https://buefy.org/documentation/pagination/
2. Click "1." and then the **right arrow**

### Expected behavior

Pagination styling is OK

<img width="392" alt="screenshot_1287" src="https://user-images.githubusercontent.com/5262234/124394069-821a8e80-dcb2-11eb-978a-2edda8527517.png">

### Actual behavior

Pagination styling is bad - as per screenshot.

![IMG_0675 2](https://user-images.githubusercontent.com/5262234/124394054-7038eb80-dcb2-11eb-9516-7af7774cc470.PNG)

### Notes

Cannot reproduce on Android or OS X versions of Firefox/Safari/Chrome. Using remote Safari debugging, the output of the HTML on iOS VS desktop is the same.

**Comment by nakedgun** [comment] 2021-07-20 04:03
@jtommy After investigating more, the issue is with this bit of CSS:

https://github.com/buefy/buefy/blob/c8da4f5f26f45120af76ce1a1afb33d86ca2203e/src/scss/components/_pagination.scss#L22

Which causes problems on iOS. To workaround this in my app, I overrode this with `pointer-events: auto !important`. But for buefy, the rule can probably just be removed.

**Comment by wesdevpro** [comment] 2023-08-02 02:03
> @jtommy After investigating more, the issue is with this bit of CSS:
> 
> https://github.com/buefy/buefy/blob/c8da4f5f26f45120af76ce1a1afb33d86ca2203e/src/scss/components/_pagination.scss#L22
> 
> Which causes problems on iOS. To workaround this in my app, I overrode this with `pointer-events: auto !important`. But for buefy, the rule can probably just be removed.

I will take a look into this. I know Buefy also has an issue with CSS and Font Icons on mobile

**Comment by wesdevpro** [comment] 2023-08-02 02:08
@nakedgun 

> The pointer-events [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) property sets under what circumstances (if any) a particular graphic element can become the [target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) of pointer events.
> Source: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

I don't see a reason why pointer-event's would hide the content of an element. There must be some other underlying issues with the CSS.

**Comment by wesdevpro** [comment] 2023-11-04 18:22
@nakedgun I pulled up https://buefy.org/documentation/pagination/ on my iPhone and for some reason I can not reproduce the error that you have.

**Comment by wesdevpro** [comment] 2024-01-20 02:14
Closing because we could not reproduce the problem listed in the issue above. Please reopen this issue if you have any information that would help us reproduce this problem.

**Closed by wesdevpro** 2024-01-20 02:14 UTC
Labels: help wanted, contribution welcome, improvement
