### ISSUE TITLE
New navbar not displaying anything

### ISSUE THREAD

**Issue by TanelTerras** [buefy/buefy#1618] opened 2019-08-01 17:17 UTC
### Overview of the problem

**Buefy** version: [0.8.0]
**Vuejs** version: [2.6.10]
**Win10/Chrome75**:

### Description

Navbar does not seem to work correctly, b-navbar-item seems to not do anything?
I am really inexperienced so i am sorry if i am missing something myself but it seems to me that i dont.

### Steps to reproduce

1. vue install .
2. npm install buefy
3. copy-paste the navbar example and make sure component logic is correct
4. navbar empty space is seen, no navbar-items created
5. same thing is also seen in codepen navbar example

### Expected behavior

exmaple code works out of the box and navbar conent can be seen

### Actual behavior

empty space for navbar but no content

**Comment by service-paradis** [comment] 2019-08-01 17:59
I can confirm. The Codepen for Navbar in documentation does not work

**Comment by brocgailit** [comment] 2019-08-01 18:07
Confirmed here as well.  Some issue with the `b-navbar-item` functional template?

I ended up dropping the `b-navbar-item`. Simply using Bulma's `navbar-item` class on the items works as intended.

**Comment by jtommy** [comment] 2019-08-01 18:09
The issue is about self closing tags in a simple html page (cdn)

**Comment by brocgailit** [comment] 2019-08-01 18:46
@jtommy Your comment doesn't seem to be relevant, helpful, or productive. self closing tags? a simple html page? content delivery network?  Its not clear what any of these things have in common with @TanelTerras's issue of the navbar items not working in the navbar component.

**Comment by jtommy** [comment] 2019-08-01 19:19
I found out an error in the docs but for an other component, I'll take a look about it right now

**Closed** 2019-08-01 21:03 UTC

**Comment by karlymraud** [comment] 2019-10-18 02:00
I'm still seeing this issue. I followed the exact same steps from the docs.
vue in

1. installed vue
2. npm install buefy
3. copy-paste the navbar example and make sure component logic is correct
4. navbar empty space is seen, no navbar-items created
5. same thing is also seen in codepen navbar example

It seems like whatever is within a `<template>` tag  when nested in `<b-navbar>` does not show

**Comment by service-paradis** [comment] 2019-10-18 17:30
Which version of Buefy are you using?

**Comment by karlymraud** [comment] 2019-10-23 03:23
current `"buefy": "^0.8.6"`

**Comment by service-paradis** [comment] 2019-10-23 12:52
@karlymraud 
Can you reproduce this in a codepen or something?

**Comment by karlymraud** [comment] 2019-10-31 14:52
@service-paradis nvm fixed, sorry and thanks for the response!
