### ISSUE TITLE
Incorrect scss filepath in buefy-build.scss

### ISSUE THREAD

**Issue by nonsugarless** [buefy/buefy#3404] opened 2021-07-04 05:41 UTC
### Overview of the problem

**Buefy** version: [0.9.8]
**Vuejs** version: [2.6.14]
**OS**:macOS Catalina

### Description

Compile error occurs if I add import of `buefy/src/scss/buefy-build` because of using incorrect path as below example. 
e.g. `"../../node_modules/bulma/sass/utilities/functions";`
```sh
ERROR  Failed to compile with 1 errors                             friendly-errors 13:55:55


 ERROR  in ./app/assets/sass/main.scss                              friendly-errors 13:55:55

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):  friendly-errors 13:55:55
SassError: File to import not found or unreadable: ../../node_modules/bulma/sass/utilities/functions.
        on line 1 of node_modules/buefy/src/scss/buefy-build.scss
        from line 2 of app/assets/sass/libs/_all.scss
        from line 5 of app/assets/sass/main.scss
>> @import "../../node_modules/bulma/sass/utilities/functions";
```
### Steps to reproduce

1. Import latest buefy 
2. Add `@import "~buefy/src/scss/buefy-build";` to my project scss

### Expected behavior
Fix paths to file in `node_modules`

### Actual behavior
Scss files which are import from `buefy-build.scss` can't be compiled.

**Comment by service-paradis** [comment] 2021-07-10 15:34
Duplicate of #3361

**Closed by service-paradis** 2021-07-10 15:34 UTC
