### ISSUE TITLE
Datepicker on version [0.9.8]  will break if initial v-model value is "null"

### ISSUE THREAD

**Issue by re2005** [buefy/buefy#3436] opened 2021-07-28 13:46 UTC
### Overview of the problem

Datepicker when set to RANGE will break if the v-model is null

**Buefy** version: 0.9.8
**Vuejs** version: 2.6.12
**OS/Browser**: ALL

### Description

```
<b-datepicker
 placeholder="Click to select..."
  v-model="dates"
   range
/>

<script>
export default {
 data() {
   return {
     dates: null
    }
   }
}
</script>

```

### Steps to reproduce

Set the v-model to null

### Expected behavior

Previous versions that wouldn't be a problem.

### Actual behavior

Error:

vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'length' of undefined at VueComponent.updateInternalState

<img width="627" alt="Screenshot 2021-07-28 at 15 45 11" src="https://user-images.githubusercontent.com/2920357/127333034-f1fb1b4d-b729-4293-ac76-60b8f86b4b61.png">

**Comment by mouadTaoussi** [comment] 2021-07-28 13:49
Are you gonna work on it?

**Comment by re2005** [comment] 2021-07-28 13:55
Suspect this has something to do with it:

<img width="585" alt="Screenshot 2021-07-28 at 15 50 02" src="https://user-images.githubusercontent.com/2920357/127334670-57e99a91-ee4b-4655-b049-d8c6a745eecb.png">

**Comment by mouadTaoussi** [comment] 2021-07-28 13:57
Might be! You gonna fix it right?

**Comment by re2005** [comment] 2021-07-28 14:41
First I need to know from @apauly who made the last change on the Datepicker component.
Whats wrong with the initial value being NULL ?

**Comment by apauly** [comment] 2021-07-28 16:25
I‘m a bit confused. My [PR](https://github.com/buefy/buefy/pull/3401) should have fixed that exact issue.
The problem before my PR was, that `length` was getting called for `this.dateSelected` even if it was `undefined`

**Comment by re2005** [comment] 2021-07-29 07:39
@apauly do you may have time to check one more time?

**Comment by apauly** [comment] 2021-07-29 12:16
Yeah, I can have another look at it but probably not before the weekend

**Comment by apauly** [comment] 2021-08-01 19:44
Here's a small [fiddle](https://jsfiddle.net/Le4vpdu5/2/)

I can confirm the behaviour you described. With v0.9.8 you'll get the error if you try to select a date. This does not happen with a previous version (e.g. 0.9.7).

But it actually seems as if the fix from my [PR](https://github.com/buefy/buefy/pull/3401) didn't make it into the release - at least I see the previous code here:
[https://unpkg.com/buefy@0.9.8/dist/buefy.js](https://unpkg.com/buefy@0.9.8/dist/buefy.js)

So I'm not sure what caused the change, but it might be fixed on the dev branch already.

**Comment by re2005** [comment] 2021-08-02 07:13
@jtommy My friend! Could you please check this one. As @apauly mentioned his fixes on the [PR](https://github.com/buefy/buefy/pull/3401) didn't make to he on the last release 0.9.8.

Thanks :)

**Comment by jtommy** [comment] 2021-08-02 17:58
Yes, it's right because I released the the last version before it

**Closed by jtommy** 2021-08-02 17:58 UTC
