### ISSUE TITLE
ReferenceError: HTMLElement is not defined

### ISSUE THREAD

**Issue by kieusonlam** [buefy/buefy#720] opened 2018-03-24 14:42 UTC
I get this error when using Buefy v0.6.4 with Nuxt project just on today. It used to work normaly before I run "npm install". I did try to downgrade all update, but It still not work.

Then I try to generate new project using this starter template (update nuxt to 1.4.0) https://github.com/nuxt-community/starter-template and use it with buefy. But still got same errors.

Here is what I have in the console.

```
{ ReferenceError: HTMLElement is not defined
    at Object.defineProperty.value (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:103177)
    at t (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:377)
    at Object.<anonymous> (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:150180)
    at t (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:377)
    at Object.<anonymous> (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:132652)
    at t (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:377)
    at Object.defineProperty.value (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:78957)
    at t (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:377)
    at Object.<anonymous> (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:190387)
    at t (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:377)
    at e.exports.e (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:761)
    at C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:772
    at n (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:143)
    at Object.<anonymous> (C:\Users\kieus\Desktop\web\node_modules\buefy\lib\index.js:1:254)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at r (C:\Users\kieus\Desktop\web\node_modules\vue-server-renderer\build.js:8147:16) statusCode: 500, name: 'ReferenceError' }
```
Any idea?

**Comment by wopian** [comment] 2018-03-24 15:50
Duplicate of #712

**Comment by kieusonlam** [comment] 2018-03-24 15:52
@wopian thanks for letting me know.

**Closed** 2018-03-24 15:51 UTC
