### ISSUE TITLE
Drop-down borders are cut off

### ISSUE THREAD

**Issue by Dave3of5** [buefy/buefy#1559] opened 2019-07-14 15:02 UTC
# Overview of the problem

The border of the drop-down are being cut off slightly.

**Buefy** version: Latest
**Vuejs** version: Latest
**OS/Browser**: Windows 10 Latest Chrome Latest

### Description

The border of the drop-down are being cut off slightly.

### Steps to reproduce

Goto https://buefy.org/documentation/select/

Most of the dropdowns on this page have their borders cutoff (Only the bottom and the right most border are affected it seems):

![image](https://user-images.githubusercontent.com/13622748/61185366-78746800-a650-11e9-92db-11b2f2b5891f.png)

Zooming in and out fixes this issue.

Edit: Please Note this only happens with the Scale and layout settings are set to 125% and chrome zoom level is 100% or 90%.

### Expected behavior

You should see the blue borders in the above screenshot

### Actual behavior

They are missing.

Seeing this in my project and it's bugging me slightly. I know it's minor but wondering if anyone knows why this is happening.

**Comment by service-paradis** [comment] 2019-07-18 13:54
Unable to reproduce on my side.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-20 22:53
![изображение](https://user-images.githubusercontent.com/9306996/61584987-abdc5880-ab62-11e9-9f92-fd7e13ca0332.png)
![изображение](https://user-images.githubusercontent.com/9306996/61584991-b39bfd00-ab62-11e9-9371-cd9eb91481c2.png)
![изображение](https://user-images.githubusercontent.com/9306996/61584992-bdbdfb80-ab62-11e9-9f5a-9ac21ef6619a.png)
how reproduce?

**Comment by Dave3of5** [comment] 2019-07-28 15:23
Says on the ticket how to reproduce also says I think it's due to zoom level as it clears on zoom level.

**Comment by DevGoslinga** [comment] 2019-08-23 14:27
I can confirm this issue it probably  has to do with the setting shown in the picture below:
![Capture](https://user-images.githubusercontent.com/17737843/63599917-d9ce1600-c5c2-11e9-9c73-9823547a0fdd.PNG)

**Comment by service-paradis** [comment] 2019-09-27 18:52
Still cannot reproduce the issue on my side.

Did you try if it does the same thing using the [bulma select](https://bulma.io/documentation/form/select/)?
If so, you should open your issue [there](https://github.com/jgthms/bulma/issues).

**Comment by DevGoslinga** [comment] 2019-09-28 03:50
bulma-select looks fine on Chrome and using Windows scaling but the buefy-select has cut off borders.

**Comment by Dave3of5** [comment] 2019-10-21 12:36
Not sure why this is difficult to reproduce. On chrome on window zoom in and out and the buefy select borders are cut off. P.S. it's not happening on the bulma select only on buefy.

**Comment by yxngl** [comment] 2019-10-21 16:38
I can reproduce on some selects for both Buefy and Bulma, but it also depends on the window width. 

See  one of the Bulma example below and observe the right border of the 3rd and 4th selects.
![select](https://user-images.githubusercontent.com/1696853/67224562-19648300-f3f7-11e9-97ef-e44400beab1c.gif)

**Comment by wesdevpro** [comment] 2024-01-20 02:50
Closing this issue because we cannot reproduce this on Windows 10 with Chrome(Zomming Test and Resizing Test). If you find any other information on how to reproduce this please reopen this issue. Thank You!

**Closed by wesdevpro** 2024-01-20 02:50 UTC
Labels: bulma, browser
