### ISSUE TITLE
b-numberinput doesn't handle a range with a negative minimum value correctly

### ISSUE THREAD

**Issue by navmed** [buefy/buefy#2904] opened 2020-09-19 16:04 UTC
### Overview of the problem
b-numberinput doesn't go below 0 if the minimum is a negative number and the default value is positive

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.12
**OS/Browser**: Windows/Chrome

### Description

I have a b-numberinput with a min of -3 and max of 3. If it starts at 1, I'd expect clicking - would go to 0, -1, -2 and stop at -3. It however doesn't go below 0.

### Steps to reproduce

1. Click the "-" button twice

### Expected behavior

It should go to 0, then -1, -2, -3 and stop at -3

### Actual behavior

It goes to 0, then 3. 

[https://codepen.io/navmed/pen/poyxZgo?editors=1010](https://codepen.io/navmed/pen/poyxZgo?editors=1010)

**Comment by jtommy** [comment] 2020-09-19 16:52
You are right, there is a wrong check on internal value

**Comment by damian-bal** [comment] 2020-09-20 17:15
Hello, is it ok to take this ticket? I think that I know what the issue is.

**Comment by jtommy** [comment] 2020-09-20 17:45
I have to fix it

**Comment by damian-bal** [comment] 2020-09-20 17:45
well ok, created PR anyway https://github.com/buefy/buefy/pull/2906, should I close it?

**Comment by jtommy** [comment] 2020-09-20 17:46
Just merged, thanks

**Closed by damian-bal** 2020-09-20 17:45 UTC
Labels: bug

**Comment by damian-bal** [comment] 2020-09-20 17:47
Thanks

**Comment by navmed** [comment] 2020-11-25 01:10
Is this fix released in 0.9.4? I'm still seeing the same problem.
