### ISSUE TITLE
Changing defaultIconPack does not affect b-notification components

### ISSUE THREAD

**Issue by mtancoigne** [buefy/buefy#147] opened 2017-07-01 20:51 UTC
### Overview of the problem

**Buefy** version: [0.4.4]
**Vuejs** version: [2.2.2]
**OS/Browser**: Linux / Chrome 59

### Description

Changing `defaultIconPack` does not affect `b-notification` components

### Steps to reproduce
1. Setup Vue + Buefy + FontAwesome with this configuration:
```js
Vue.use(Buefy, {
  defaultIconPack: 'fa',
});
```
2. Add a `b-notification somewhere with `has-icon` and `type="danger"` attributes:
```vue
<b-notification :active="error" type="is-danger" has-icon :closable="false">
  ... some message
</b-notification>
```

### Expected behavior
The expected result is the one from documentation, with a fontawesome icon:
![selection_007](https://user-images.githubusercontent.com/1732268/27765358-1c154402-5eaf-11e7-809d-60886a6414cc.png)

### Actual behavior
The custom `defaultIconPack` option is not applied, and the `mdi` icon is loaded:
![selection_008](https://user-images.githubusercontent.com/1732268/27765364-5dabd1c4-5eaf-11e7-80f4-c64b6cdf9318.png)

A `console.log(config.defaultIconPack)` in the `data()` method of the `b-icon` component returns `mdi`.
I haven't tried on other components, so i don't know if it's a global issue, or only for `b-notification`

**Comment by rafaelpimpa** [comment] 2017-07-03 11:23
I've just tested in 2 different projects and it's working fine 🤔 , is it happening on every component?

**Comment by mtancoigne** [comment] 2017-07-07 11:37
Hum, I haven't tested on more components, so i'll try to do this this weekend.

**Comment by OzairP** [comment] 2017-07-08 21:19
I'm experiencing this issue as well. I'm using Material Design Icons however and importing it into my stylesheet via NPM rather than the MDI CDN.

**Comment by pflirae** [comment] 2018-08-15 03:40
I have observed the problem that mtancoigne described on differente components, and to reproduce it, the only acction needed is to not include the mdi icons on your project, removing the <link ...> instruction for mdi.
It fails because the is-xyz type was hardcoded to use mdi and ignores the defaultIconPack configuration, maybe on future release this will be fixed, by the momento the mdi icons must be imported even if your project do not need them, so the is-xyz type shows an icon.

**Comment by jweultjes** [comment] 2019-04-09 08:23
I _think_ that I've found a similar problem. In our project we use fontawesome for our icons as described below.
```
Vue.use(Buefy, {
  defaultIconPack: 'fas',
});
```

I've tested the b-notification component that doesn't seem to work for mtancoigne. That one renders fine. However, b-input doesn't seem to respect this option and does try to render with mdi icons instead of fontawesome ones (unless I pass the `icon-pack="fas"` parameter). 

**Buefy** version: [0.7.3]
**Vuejs** version: [2.6.10]
**OS/Browser**: Ubuntu 18.04 / Firefox 66.0.2 & Chromium 73.0.3683.75

**Comment by jtommy** [comment] 2019-04-09 19:45
Are using bundle or individual components ?

**Comment by jweultjes** [comment] 2019-04-10 07:11
I feel like a proper idiot now. My IDE automatically included b-input as an individual component. Removing that import statement fixed my issue.

**Closed** 2019-04-10 07:13 UTC
Labels: need more info
