### ISSUE TITLE
TimePicker timeFormatter doesn't seem to be used

### ISSUE THREAD

**Issue by zedrdave** [buefy/buefy#1433] opened 2019-05-26 10:39 UTC
**Buefy** version: 0.7.6
**Vuejs** version: 2.6.10

### Steps to reproduce

```
<b-timepicker 
v-model="myTime"
:time-formatter="myTimeFormatter"
/>
[...]
methods: {
myTimeFormatter(date) {
      console.info("debug!")
      return dayjs.utc(date).format("HH:mm");
    },
}
```

### Expected behavior

`myTimeFormatter` gets called and debug message displayed.

### Actual behavior

Formatter function is never called.
Looking at the code for TimePickerMixin, the prop is read, but never used (only the formatter from config).

**Comment by wesdevpro** [comment] 2023-08-11 14:54
> still doesn't work with the latest version

Please send more information showing what issues you are currently having. Thanks

**Comment by guestisp** [comment] 2023-08-11 15:17
> Please send more information showing what issues you are currently having. Thanks

Exactly the same as first message. The `:time-formatter` or `:time-parser` are not called.. I've put a `console.log` in the custom function and it's never called

**Comment by kikuomax** [comment] 2023-12-27 02:22
@guestisp @wesdevpro I tested the behavior of `BTimepicker` with the following code:
```vue
<template>
    <div class="container is-max-desktop">
        <b-timepicker
            v-model="dt"
            :time-parser="timeParser"
            :time-formatter="timeFormatter"
            editable
        />
    </div>
</template>

<script>
export default {
    data() {
        return {
            dt: new Date()
        }
    },
    methods: {
        timeParser(timeStr) {
            console.log('timeParser called', timeStr)
            const [h, m] = timeStr.split(':')
            const dt = new Date()
            dt.setHours(parseInt(h))
            dt.setMinutes(parseInt(m))
            return dt
        },
        timeFormatter(dt) {
            console.log('timeFormatter called', dt)
            const h = dt.getHours().toString().padStart(2, '0')
            const m = dt.getMinutes().toString().padStart(2, '0')
            return `${h}:${m}`
        }
    }
}
</script>
```
As far as I tested, both `timeFormatter` and `timeParser` were called:
![image](https://github.com/buefy/buefy/assets/3257531/6c256109-b9c7-4884-85d2-7947326f5654)

**Comment by wesdevpro** [comment] 2023-12-27 02:44
> Exactly the same as first message. The `:time-formatter` or `:time-parser` are not called.. I've put a `console.log` in the custom function and it's never called

Interesting.

**Comment by wesdevpro** [comment] 2024-01-20 02:12
Closing this because we cannot reproduce this issue. @guestisp If you could reopen when you can provide more information to reproduce this problem. Thank you!

**Closed by wesdevpro** 2024-01-20 02:12 UTC
Labels: need more info
