### ISSUE TITLE
Autocomplete make one extra AJAX call after selecting option

### ISSUE THREAD

**Issue by ibeex** [buefy/buefy#850] opened 2018-06-12 07:15 UTC
### Overview of the problem

**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: Linux/Firefox

### Description

Autocomplete using async,
after selecting option from dropdown menu there is one more call to async API.

### Steps to reproduce

1. Open Async with custom template example page (or make own one)
2. Watch network calls in developer console
3. type seach terrm 
4. There is few ajax calls and main search call
5. Select item from dropdown menu
6. There is ajax call with selected item as search tearm

### Expected behavior

Item should be selected, withouth ajax call

### Actual behavior

There is one more ajax call to search API

**Comment by adrlen** [comment] 2018-06-12 07:55
I think it's a duplicate of #721

**Comment by ibeex** [comment] 2018-06-12 09:58
it looks like, mybe documentation example can use solution?

**Comment by jtommy** [comment] 2018-06-21 15:32
https://github.com/buefy/buefy/pull/875

**Closed by jtommy** 2018-06-21 15:32 UTC
