### ISSUE TITLE
Error `ReferenceError: HTMLElement is not defined` when using Buefy 0.6.4 with Nuxt

### ISSUE THREAD

**Issue by thommeo** [buefy/buefy#726] opened 2018-03-25 20:05 UTC
### Overview of the problem

**Buefy** version: [0.6.4]
**Vuejs** version: [2.5.16]
**OS/Browser**: nuxt v.1.4.0

### Description

Error `ReferenceError: HTMLElement is not defined` when using Buefy 0.6.4 with Nuxt

### Steps to reproduce

1. Connect Buefy to Nuxt.

`nuxt.config.js`:

```
module.exports = {
  plugins: [
    '~plugins/buefy'
  ]
}
```

`plugins/buefy.js`:

```
import Vue from 'vue'
import Buefy from 'buefy'

Vue.use(Buefy, {
  defaultIconPack: 'mdi'
})
```

2. Install Buefy 0.6.3 and generate

```
yarn add buefy@0.6.3 --exact
yarn generate
```

Success.

3. Install Buefy 0.6.4 and generate

```
yarn add buefy@0.6.4 --exact
yarn generate
```

Error:

```
 ROUTE  /

  ReferenceError: HTMLElement is not defined
  
  - server-bundle.js:10471 Object.defineProperty.value
    server-bundle.js:10471:103071
  
  - server-bundle.js:10471 t
    server-bundle.js:10471:271
  
  - server-bundle.js:10471 Object.<anonymous>
    server-bundle.js:10471:150074
  
  - server-bundle.js:10471 t
    server-bundle.js:10471:271
  
  - server-bundle.js:10471 Object.<anonymous>
    server-bundle.js:10471:132546
  
  - server-bundle.js:10471 t
    server-bundle.js:10471:271
  
  - server-bundle.js:10471 Object.defineProperty.value
    server-bundle.js:10471:78851
  
  - server-bundle.js:10471 t
    server-bundle.js:10471:271
  
  - server-bundle.js:10471 Object.<anonymous>
    server-bundle.js:10471:190281
  
  - server-bundle.js:10471 t
    server-bundle.js:10471:271
  
  - server-bundle.js:10471 e.exports.e
    server-bundle.js:10471:655
  
  - server-bundle.js:10471 
    server-bundle.js:10471:666
  
  - server-bundle.js:10471 module.exports.n
    server-bundle.js:10471:37
  
  - server-bundle.js:10471 Object.module.exports.Object.defineProperty.value
    server-bundle.js:10471:148
  
  - server-bundle.js:27 __webpack_require__
    server-bundle.js:27:30
  
  - server-bundle.js:36169 Object.<anonymous>
    server-bundle.js:36169:14
  
  - server-bundle.js:27 __webpack_require__
    server-bundle.js:27:30
  
  - server-bundle.js:30080 Object.<anonymous>
    server-bundle.js:30080:29
  
  - server-bundle.js:27 __webpack_require__
    server-bundle.js:27:30
  
  - server-bundle.js:10513 Object.<anonymous>
    server-bundle.js:10513:14
  
  - server-bundle.js:27 __webpack_require__
    server-bundle.js:27:30
  
  - server-bundle.js:92 
    server-bundle.js:92:18
```

The same is fair when run as `yarn dev`.

### Expected behavior

Successful generation of the static website.

### Actual behavior

See steps

**Comment by wopian** [comment] 2018-03-25 22:01
Duplicate of #712 - has been fixed but not released yet

@jtommy could you reopen #712 until a new version has been published to aid visibility?

**Comment by jtommy** [comment] 2018-03-25 22:02
@wopian Ok!

**Closed by jtommy** 2018-03-25 22:02 UTC
