### ISSUE TITLE
Datepicker selected wrong date on mobile

### ISSUE THREAD

**Issue by jaredpg1** [buefy/buefy#1957] opened 2019-11-05 17:04 UTC
Tested datepicker component on iOS. When selected a date with the datepicker, the wrong date is being added to the component. I've attached a screen capture of the video I took on my device.
In this image, I selected November 9, 2019, but November 8, 2019 was displayed in the datepicker component.

![ScreenGrab](https://user-images.githubusercontent.com/23516076/68228933-e6f08380-ffbb-11e9-850a-c98d4f7027a7.png)

**Comment by service-paradis** [comment] 2019-11-05 18:15
Which version of Buefy are you using?

**Comment by service-paradis** [comment] 2019-11-05 18:17
Probably related to changes made for #1591 and #1856

**Comment by jaredpg1** [comment] 2019-11-05 18:42
I'm running 0.8.6 on my own project. However, that screen grab was taken from the Buefy documentation site, so I would imagine it is using the latest version as well.

**Comment by zedrdave** [comment] 2019-11-07 09:34
On latest version (0.8.6), I am also encountering a problem with Safari on OS X:
<img width="463" alt="Screenshot 2019-11-07 at 10 23 48" src="https://user-images.githubusercontent.com/746979/68377054-03bac180-014a-11ea-812c-95c882b51e61.png">
(text below the box is the direct value of the `v-model` Date variable)

By comparison, Chrome gives out:
<img width="465" alt="Screenshot 2019-11-07 at 10 23 54" src="https://user-images.githubusercontent.com/746979/68377106-1c2adc00-014a-11ea-9110-3865bf3fdda7.png">

**Comment by service-paradis** [comment] 2019-11-07 18:53
Probably related to https://github.com/buefy/buefy/pull/1856/files
Since, the dates is created in UTC without hours. When converted back in the user Timezone, the dates can be a day before.

**Comment by jtommy** [comment] 2019-11-07 20:20
@zedrdave print date object isn't a good way to check it

**Comment by zedrdave** [comment] 2019-11-13 18:57
@jtommy Sure, but why?

In any case, that's not too relevant, since the data received in the same in both browsers and the value displayed is different.

**Comment by jtommy** [comment] 2019-11-13 19:35
@zedrdave try to print only `getDate()`. You should see the same day

**Comment by zedrdave** [comment] 2019-11-13 19:48
@jtommy Sorry if this was unclear. The bug is not with what's printed through `v-model`, the bug is with what gets displayed in the datepicker itself. As you can see, with the same input, I get a different date between browsers (Safari is off by 1 day).

**Comment by jtommy** [comment] 2019-11-13 19:56
Do you mean clicking on a date cell you see a +1 date in the date input?

**Comment by zedrdave** [comment] 2019-11-13 20:01
The full-size calendar display the right date (14/7), as do every other parts of the app. It's just the input field (as shown above) that shows a -1 date (13/7) on Safari.

**Comment by jtommy** [comment] 2019-11-13 20:42
Do you see a correct day using Chrome? Unfortunately I cannot test it in a iOS system

**Comment by zedrdave** [comment] 2019-11-13 20:45
Yes, as the second screenshot shows, the date shows correctly in Chrome.
This is Safari for *OS X*, however, not iOS (but it seems the bug happens in both).

**Comment by jtommy** [comment] 2019-11-13 20:46
I mean on mobile and desktop Apple systems

**Comment by jtommy** [comment] 2020-01-18 10:29
@zedrdave is already an issue ?

**Comment by zedrdave** [comment] 2020-01-24 11:24
@jtommy I'll try to test, but this is currently a bit difficult, since I am running on a fork of Buefy that adds the timezone support I need…

**Comment by jtommy** [comment] 2020-01-29 17:17
@zedrdave does it work with your PR (merged)

**Comment by zedrdave** [comment] 2020-01-29 17:18
I can't check on the relevant codebase right now, but will check later tonight and let you know!

**Comment by zedrdave** [comment] 2020-01-30 08:52
@jtommy Just tested and same problem is still happening… 😕

First on OSX Chrome (working as expected):
<img width="462" alt="Screenshot 2020-01-30 at 09 48 00" src="https://user-images.githubusercontent.com/746979/73433899-f9255800-4345-11ea-86df-a2ba06070caf.png">

Second on OSX Safari (date displayed is off by one day): 
<img width="521" alt="Screenshot 2020-01-30 at 09 47 10" src="https://user-images.githubusercontent.com/746979/73433903-fb87b200-4345-11ea-890e-de8dc02a97a4.png">

**Comment by jtommy** [comment] 2020-01-30 11:30
@zedrdave what's your code to format the date ?

**Comment by zedrdave** [comment] 2020-01-30 12:20
```
                <b-datepicker
                  expanded
                  v-model="dateOfBirth"
                  @input="handleChange"
                  :date-formatter="this.localeBirthdate"
                />
[...]
  localeBirthdate: (d) => {
    return d ? d.toLocaleDateString([], { year: 'numeric', month: 'long', day: 'numeric' }) : null
  },
```

But even if I remove the formatter altogether:
```
                <b-datepicker
                  expanded
                  v-model="dateOfBirth"
                />
```

the result is the same…

**Comment by jtommy** [comment] 2020-01-30 12:47
@zedrdave did you try to see the date object? For example using `d.getDate()`

**Comment by zedrdave** [comment] 2020-01-30 22:24
@jtommy oddly enough, both browsers show the right hour for `getDate()`. On the other hand `toLocaleDateString` does show the shifted date. Not sure what the different values for `tzOffset` mean…

Chrome:
<img width="444" alt="Screenshot 2020-01-30 at 23 18 57" src="https://user-images.githubusercontent.com/746979/73495826-9a98c200-43b7-11ea-9c3e-38b015e2d231.png">

Safari:
<img width="442" alt="Screenshot 2020-01-30 at 23 19 06" src="https://user-images.githubusercontent.com/746979/73495839-a1bfd000-43b7-11ea-8573-09ffe67e4f37.png">

**Comment by jtommy** [comment] 2020-01-31 07:15
@zedrdave btw I think will be add this idea https://github.com/buefy/buefy/issues/1486. You could try this way to format the date

**Comment by zedrdave** [comment] 2020-01-31 21:58
That sounds good. I'll try and have a look over the weekend.

**Comment by davidmeeker** [comment] 2020-04-17 21:15
The issue seems to be that defaultDateFormatter yields incorrect results on Safari (both desktop OS X and iOS) for spring dates far in the past (likely where DST rules were different). 

Chrome and Firefox both yield these results, which are as expected: 

>new Date("1977/4/1").toLocaleDateString()
>"4/1/1977"
>new Date("2020/4/1").toLocaleDateString()
>"4/1/2020"

Compare to Safari: 

> new Date("2020/4/1").toLocaleDateString()
> "4/1/2020"
> new Date("1978/4/1").toLocaleDateString()
> **"3/31/1978"** (wrong)

Examining the full string (still in Safari) shows we've lost an hour:

> new Date("1978/4/1").toLocaleString()
> "3/31/1978, 11:00:00 PM"

This appears to be due to Safari not properly handling the historical changes in the the DST rules of my timezone (US Central).

Safari:
> new Date("2020/4/1").getTimezoneOffset()
> 300
> new Date("1978/4/1").getTimezoneOffset()
> 300 (wrong)

Chrome + Firefox:

> new Date("2020/4/1").getTimezoneOffset()
> 300
> new Date("1978/4/1").getTimezoneOffset()
> 360

Given that the issue is that we're aiming for midnight and thus that one hour variance is causing an issue, I'd recommend we instead aim for noon by changing this block within defaultDateFormatter:

```
        const yyyyMMdd = date.getFullYear() +
            '/' + (date.getMonth() + 1) +
            '/' + date.getDate()
        const d = new Date(yyyyMMdd)

```

to instead be:

```
        const d = new Date(date.getFullYear(), date.getMonth(), date.getDate(), 12)

```


Results on Safari:

> new Date(1978,3,1,12).toLocaleString()
> "4/1/1978, 11:00:00 AM"
> new Date(1978,3,1,12).toLocaleDateString()
> "4/1/1978"

And Firefox / Chrome:

> new Date(1978,3,1,12).toLocaleString()
> "4/1/1978, 12:00:00 PM"
> new Date(1978,3,1,12).toLocaleDateString()
> "4/1/1978"

**Comment by zedrdave** [comment] 2020-04-18 08:51
@davidmeeker Good catch!
I have tested and indeed the bug only happens for dates further back than April 4, 1977 with my computer locale…

Modifying the date formatter as you suggest does indeed fix the problem!

**Comment by jtommy** [comment] 2020-04-18 12:27
@zedrdave @davidmeeker so is there a universal fix to add in the core code ?

**Comment by davidmeeker** [comment] 2020-04-18 12:55
The fix I suggested above to defaultDateFormatter is universal. I can submit a PR at some point this weekend if that would be helpful.

**Comment by jtommy** [comment] 2020-04-18 13:07
@davidmeeker sure, thanks! So i can test it

**Closed** 2020-04-22 17:15 UTC
Labels: need-investigation

**Comment by mrtnzagustin** [comment] 2020-08-06 00:36
This doesnt work in Chrome nor Firefox. Could you extend it to others user agents?
