### ISSUE TITLE
@change event is not getting fired for b-tabs using Buefy version 0.9.0

### ISSUE THREAD

**Issue by vinod454** [buefy/buefy#3393] opened 2021-06-29 07:03 UTC
### Overview of the problem

**Buefy** version: [0.9.0]
**Vuejs** version: [2.6.11]
**OS/Browser**: Windows 10

### Description

I used activeTabId in the v-model in b-tabs. However, the change event is not getting triggered when the value of activeTabId is changed.

### Steps to reproduce

<b-tabs
v-model="activeTabId "
:animated="false"
size="is-small"
@change="onTabChange"

Here, we have activeTabId which is an int data variable used in the v-model of b-tabs. We maintain one bTabArray which holds the information about open tabs. If we add a new tab entry in the array, the value of activeTabId gets changed.

data() {
    return {
        activeTabId : 0
    }
}

Also, we have one method

methods: {
  async onTabChange(value) {
      // function body
  }
}

Here, onTabChange is not getting triggered while the value of activeTabId is changed.

### Expected behavior

onTabChange should trigger as the value of activeTabId is changed.

### Actual behavior

onTabChange is not getting triggered as the value of activeTabId changes.

**Comment by service-paradis** [comment] 2021-06-29 12:39
Duplicate of #3386

**Closed by service-paradis** 2021-06-29 12:39 UTC
